dist: bionic
addons:
  chrome: stable
language: python
python:
    - "3.6"

install:
  - "pip install -r requirements_dev.txt"
  - "export LATEST_CHROMEDRIVER=$(wget -q -O - http://chromedriver.storage.googleapis.com/LATEST_RELEASE)"
  - "wget http://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER/chromedriver_linux64.zip; unzip chromedriver_linux64.zip -d chromedriver; export PATH=$PATH:`pwd`/chromedriver"


script:
    - "flake8 ."
    - "python -m pytest"
