name: Test registry
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x64
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements_dev.txt') }}
    - run: pip install -r requirements_dev.txt
    - run: pip install -r requirements.txt
    - run: python -m pytest tests/
    - run: MODE="dashboard" python -m pytest tests_dashboard/

